_:

# criomos-lib — Sema-style namespace of helpers. Keep names flat. No
# type-suffixed names.

let
  inherit (builtins)
    fromJSON
    functionArgs
    head
    intersectAttrs
    readFile
    sort
    tail
    toJSON
    ;
in
rec {

  # ─── Horizon ─────────────────────────────────────────────────────────

  # Read an enriched horizon JSON file (produced by `horizon-cli
  # --format json`) and return its attrset. Pure JSON parsing — all
  # projection happens upstream in horizon-rs.
  #
  # Consumers (typically the wrapper flake generated by the build
  # orchestrator tool) wire this into the `horizon` specialArg of
  # `nixosSystem`.
  mkHorizon = horizonJsonPath: fromJSON (readFile horizonJsonPath);

  # ─── List helpers ────────────────────────────────────────────────────

  lowestOf = list: head (sort (a: b: a < b) list);
  highestOf = list: tail (sort (a: b: a < b) list);

  # ─── JSON helpers ────────────────────────────────────────────────────

  importJSON = filePath: fromJSON (readFile filePath);

  # Call a lambda with only the args it asks for, drawn from a closure.
  callWith =
    lambda: closure:
    let
      required = functionArgs lambda;
      present = intersectAttrs required closure;
    in
    lambda present;

  # ─── Magnitude ladder ────────────────────────────────────────────────

  # 0 None / 1 Min / 2 Med / 3 Max. Matches horizon-rs Magnitude.
  mkSizeAtLeast = size: {
    min = size >= 1;
    med = size >= 2;
    max = size == 3;
  };

  matchSize =
    size: ifNon: ifMin: ifMed: ifMax:
    let
      s = mkSizeAtLeast size;
    in
    if s.max then ifMax
    else if s.med then ifMed
    else if s.min then ifMin
    else ifNon;

  # ─── Settings merge ──────────────────────────────────────────────────

  # Deep-merge a nix-declared JSON object into a mutable settings file.
  # Nix-declared keys win; user-added keys are preserved.
  mkJsonMerge =
    { lib, pkgs, file, nixSettings }:
    let
      nixJsonFile = pkgs.writeText "nix-settings.json" (toJSON nixSettings);
      jq = "${pkgs.jq}/bin/jq";
    in
    lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      target="${file}"
      mkdir -p "$(dirname "$target")"
      if [ -f "$target" ]; then
        ${jq} -s '.[0] * .[1]' "$target" ${nixJsonFile} > "$target.tmp"
        mv "$target.tmp" "$target"
      else
        cp ${nixJsonFile} "$target"
      fi
    '';
}
